// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	StockPrice        float64     `json:"stock_price"`
	OutstandingShares int         `json:"outstanding_shares"`
	Founded           int         `json:"founded"`
	Headquarters      string      `json:"headquarters"`
	Industry          string      `json:"industry"`
	Employees         []*Employee `json:"employees"`
}

type Employee struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Updated bool   `json:"updated"`
}

type Mutation struct {
}

type Query struct {
}
